[project]
name = "radar-simulation-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "numpy>=2.3.5",
    "torch>=2.9.1",
]
